Add ccache to all jenkins images
osuosl/osl-dockerfiles pull request #17
Opened 2018-04-24 23:29 UTC by ramereth

This also pulls in some standardization on the Dockerfile and how we build these images. Please see individual commits for more details.

2018-04-24 23:30 UTC, ramereth commented
![](https://github.trello.services/images/mini-trello-icon.png) [#29980: pytorch community request : cache folder for docker container](https://trello.com/c/OxnhKak7/699-29980-pytorch-community-request-cache-folder-for-docker-container)

2018-04-25 17:13 UTC, Codysseus requested changes

2018-04-25 17:13 UTC, Codysseus commented on centos-ppc64le-cuda/Dockerfile
> +    yum clean all && \
`yum clean all` twice?

2018-04-25 17:13 UTC, Codysseus commented on centos-ppc64le-cuda/Dockerfile
> +    rm -rf /var/cache/yum
This is what I get when I try to build it:
```
Step 6/30 : RUN yum upgrade -y &&     yum clean all &&     rm -rf /var/cache/yum
 ---> Running in 194d9572b956
standard_init_linux.go:185: exec user process caused "no such file or directory"
```

2018-04-25 17:25 UTC, Codysseus commented on centos-ppc64le-cuda/Dockerfile
> +    rm -rf /var/cache/yum
I ran this on openpower8 and it built, but now I can't find the container.

2018-04-26 17:40 UTC, ramereth commented
@Codysseus can you please take another look at this?

2018-04-27 18:29 UTC, Codysseus requested changes
It seems the s390x builds have problems :/
```
Step 11/28 : RUN groupadd -g ${gid} ${group}     && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"
 ---> Running in c2f68355e6fe
standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c groupadd -g ${gid} ${group}     && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"' returned a non-zero code: 1
[root@openpower8 debian-s390x]# 

Step 11/29 : RUN groupadd -g ${gid} ${group}     && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"
 ---> Running in 83906727b5ae
standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c groupadd -g ${gid} ${group}     && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"' returned a non-zero code: 1
[root@openpower8 fedora-s390x]# 

Step 11/28 : RUN groupadd -g ${gid} ${group}     && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"
 ---> Running in 23d0742e662a
standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c groupadd -g ${gid} ${group}     && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"' returned a non-zero code: 1
[root@openpower8 ubuntu-s390x]# 
```

2018-04-27 19:34 UTC, Codysseus approved these changes
Tested on s390x-docker2

2018-04-27 20:08 UTC, merged